from datetime import datetime

import numpy as np

def ns_to_datetime(ns_timestamp: int) -> datetime: ...
def us_to_datetime(us_timestamp: int) -> datetime: ...
def ms_to_datetime(ms_timestamp: int) -> datetime: ...
def s_to_datetime(s_timestamp: float) -> datetime: ...
def datetime_to_ns(dt: datetime) -> int: ...
def datetime_to_us(dt: datetime) -> int: ...
def datetime_to_ms(dt: datetime) -> int: ...
def datetime_to_s(dt: datetime) -> float: ...
def ns_array_to_datetime(ns_array: np.ndarray) -> np.ndarray: ...
def datetime_array_to_ns(dt_array: np.ndarray) -> np.ndarray: ...
def adjust_timestamp(
    timestamp: int, from_unit: str = "ns", to_unit: str = "ns"
) -> int: ...
